// Complete Windows time-zone list (tzutil IDs). `value` is the exact ID Windows
// unattend/tzutil expects — do not alter it; `label` prefixes the base-UTC offset
// for readability. Ordered by offset. Source: Windows tzutil /L.
export interface TzOption {
  label: string;
  value: string;
}

export const WINDOWS_TIMEZONES: TzOption[] = [
  { label: "(UTC-12:00) Dateline Standard Time", value: "Dateline Standard Time" },
  { label: "(UTC-11:00) UTC-11", value: "UTC-11" },
  { label: "(UTC-10:00) Aleutian Standard Time", value: "Aleutian Standard Time" },
  { label: "(UTC-10:00) Hawaiian Standard Time", value: "Hawaiian Standard Time" },
  { label: "(UTC-09:30) Marquesas Standard Time", value: "Marquesas Standard Time" },
  { label: "(UTC-09:00) Alaskan Standard Time", value: "Alaskan Standard Time" },
  { label: "(UTC-09:00) UTC-09", value: "UTC-09" },
  { label: "(UTC-08:00) Pacific Standard Time (Mexico)", value: "Pacific Standard Time (Mexico)" },
  { label: "(UTC-08:00) UTC-08", value: "UTC-08" },
  { label: "(UTC-08:00) Pacific Standard Time", value: "Pacific Standard Time" },
  { label: "(UTC-07:00) US Mountain Standard Time (Arizona)", value: "US Mountain Standard Time" },
  { label: "(UTC-07:00) Mountain Standard Time (Mexico)", value: "Mountain Standard Time (Mexico)" },
  { label: "(UTC-07:00) Mountain Standard Time", value: "Mountain Standard Time" },
  { label: "(UTC-07:00) Yukon Standard Time", value: "Yukon Standard Time" },
  { label: "(UTC-06:00) Central America Standard Time", value: "Central America Standard Time" },
  { label: "(UTC-06:00) Central Standard Time", value: "Central Standard Time" },
  { label: "(UTC-06:00) Easter Island Standard Time", value: "Easter Island Standard Time" },
  { label: "(UTC-06:00) Central Standard Time (Mexico)", value: "Central Standard Time (Mexico)" },
  { label: "(UTC-06:00) Canada Central Standard Time", value: "Canada Central Standard Time" },
  { label: "(UTC-05:00) SA Pacific Standard Time", value: "SA Pacific Standard Time" },
  { label: "(UTC-05:00) Eastern Standard Time (Mexico)", value: "Eastern Standard Time (Mexico)" },
  { label: "(UTC-05:00) Eastern Standard Time", value: "Eastern Standard Time" },
  { label: "(UTC-05:00) Haiti Standard Time", value: "Haiti Standard Time" },
  { label: "(UTC-05:00) Cuba Standard Time", value: "Cuba Standard Time" },
  { label: "(UTC-05:00) US Eastern Standard Time", value: "US Eastern Standard Time" },
  { label: "(UTC-05:00) Turks And Caicos Standard Time", value: "Turks And Caicos Standard Time" },
  { label: "(UTC-04:00) Paraguay Standard Time", value: "Paraguay Standard Time" },
  { label: "(UTC-04:00) Atlantic Standard Time", value: "Atlantic Standard Time" },
  { label: "(UTC-04:00) Venezuela Standard Time", value: "Venezuela Standard Time" },
  { label: "(UTC-04:00) Central Brazilian Standard Time", value: "Central Brazilian Standard Time" },
  { label: "(UTC-04:00) SA Western Standard Time", value: "SA Western Standard Time" },
  { label: "(UTC-04:00) Pacific SA Standard Time", value: "Pacific SA Standard Time" },
  { label: "(UTC-03:30) Newfoundland Standard Time", value: "Newfoundland Standard Time" },
  { label: "(UTC-03:00) Tocantins Standard Time", value: "Tocantins Standard Time" },
  { label: "(UTC-03:00) E. South America Standard Time", value: "E. South America Standard Time" },
  { label: "(UTC-03:00) SA Eastern Standard Time", value: "SA Eastern Standard Time" },
  { label: "(UTC-03:00) Argentina Standard Time", value: "Argentina Standard Time" },
  { label: "(UTC-03:00) Greenland Standard Time", value: "Greenland Standard Time" },
  { label: "(UTC-03:00) Montevideo Standard Time", value: "Montevideo Standard Time" },
  { label: "(UTC-03:00) Magallanes Standard Time", value: "Magallanes Standard Time" },
  { label: "(UTC-03:00) Saint Pierre Standard Time", value: "Saint Pierre Standard Time" },
  { label: "(UTC-03:00) Bahia Standard Time", value: "Bahia Standard Time" },
  { label: "(UTC-02:00) UTC-02", value: "UTC-02" },
  { label: "(UTC-02:00) Mid-Atlantic Standard Time", value: "Mid-Atlantic Standard Time" },
  { label: "(UTC-01:00) Azores Standard Time", value: "Azores Standard Time" },
  { label: "(UTC-01:00) Cape Verde Standard Time", value: "Cape Verde Standard Time" },
  { label: "(UTC+00:00) UTC", value: "UTC" },
  { label: "(UTC+00:00) GMT Standard Time", value: "GMT Standard Time" },
  { label: "(UTC+00:00) Greenwich Standard Time", value: "Greenwich Standard Time" },
  { label: "(UTC+00:00) Sao Tome Standard Time", value: "Sao Tome Standard Time" },
  { label: "(UTC+01:00) Morocco Standard Time", value: "Morocco Standard Time" },
  { label: "(UTC+01:00) W. Europe Standard Time", value: "W. Europe Standard Time" },
  { label: "(UTC+01:00) Central Europe Standard Time", value: "Central Europe Standard Time" },
  { label: "(UTC+01:00) Romance Standard Time", value: "Romance Standard Time" },
  { label: "(UTC+01:00) Central European Standard Time", value: "Central European Standard Time" },
  { label: "(UTC+01:00) W. Central Africa Standard Time", value: "W. Central Africa Standard Time" },
  { label: "(UTC+02:00) GTB Standard Time", value: "GTB Standard Time" },
  { label: "(UTC+02:00) Middle East Standard Time", value: "Middle East Standard Time" },
  { label: "(UTC+02:00) Egypt Standard Time", value: "Egypt Standard Time" },
  { label: "(UTC+02:00) E. Europe Standard Time", value: "E. Europe Standard Time" },
  { label: "(UTC+02:00) Syria Standard Time", value: "Syria Standard Time" },
  { label: "(UTC+02:00) West Bank Standard Time", value: "West Bank Standard Time" },
  { label: "(UTC+02:00) South Africa Standard Time", value: "South Africa Standard Time" },
  { label: "(UTC+02:00) FLE Standard Time", value: "FLE Standard Time" },
  { label: "(UTC+02:00) Israel Standard Time", value: "Israel Standard Time" },
  { label: "(UTC+02:00) Kaliningrad Standard Time", value: "Kaliningrad Standard Time" },
  { label: "(UTC+02:00) Sudan Standard Time", value: "Sudan Standard Time" },
  { label: "(UTC+02:00) Libya Standard Time", value: "Libya Standard Time" },
  { label: "(UTC+02:00) Namibia Standard Time", value: "Namibia Standard Time" },
  { label: "(UTC+03:00) Jordan Standard Time", value: "Jordan Standard Time" },
  { label: "(UTC+03:00) Arabic Standard Time", value: "Arabic Standard Time" },
  { label: "(UTC+03:00) Turkey Standard Time", value: "Turkey Standard Time" },
  { label: "(UTC+03:00) Arab Standard Time", value: "Arab Standard Time" },
  { label: "(UTC+03:00) Belarus Standard Time", value: "Belarus Standard Time" },
  { label: "(UTC+03:00) Russian Standard Time", value: "Russian Standard Time" },
  { label: "(UTC+03:00) E. Africa Standard Time", value: "E. Africa Standard Time" },
  { label: "(UTC+03:30) Iran Standard Time", value: "Iran Standard Time" },
  { label: "(UTC+04:00) Arabian Standard Time", value: "Arabian Standard Time" },
  { label: "(UTC+04:00) Astrakhan Standard Time", value: "Astrakhan Standard Time" },
  { label: "(UTC+04:00) Azerbaijan Standard Time", value: "Azerbaijan Standard Time" },
  { label: "(UTC+04:00) Russia Time Zone 3", value: "Russia Time Zone 3" },
  { label: "(UTC+04:00) Mauritius Standard Time", value: "Mauritius Standard Time" },
  { label: "(UTC+04:00) Saratov Standard Time", value: "Saratov Standard Time" },
  { label: "(UTC+04:00) Georgian Standard Time", value: "Georgian Standard Time" },
  { label: "(UTC+04:00) Volgograd Standard Time", value: "Volgograd Standard Time" },
  { label: "(UTC+04:00) Caucasus Standard Time", value: "Caucasus Standard Time" },
  { label: "(UTC+04:30) Afghanistan Standard Time", value: "Afghanistan Standard Time" },
  { label: "(UTC+05:00) West Asia Standard Time", value: "West Asia Standard Time" },
  { label: "(UTC+05:00) Ekaterinburg Standard Time", value: "Ekaterinburg Standard Time" },
  { label: "(UTC+05:00) Pakistan Standard Time", value: "Pakistan Standard Time" },
  { label: "(UTC+05:00) Qyzylorda Standard Time", value: "Qyzylorda Standard Time" },
  { label: "(UTC+05:30) India Standard Time", value: "India Standard Time" },
  { label: "(UTC+05:30) Sri Lanka Standard Time", value: "Sri Lanka Standard Time" },
  { label: "(UTC+05:45) Nepal Standard Time", value: "Nepal Standard Time" },
  { label: "(UTC+06:00) Central Asia Standard Time", value: "Central Asia Standard Time" },
  { label: "(UTC+06:00) Bangladesh Standard Time", value: "Bangladesh Standard Time" },
  { label: "(UTC+06:00) Omsk Standard Time", value: "Omsk Standard Time" },
  { label: "(UTC+06:30) Myanmar Standard Time", value: "Myanmar Standard Time" },
  { label: "(UTC+07:00) SE Asia Standard Time", value: "SE Asia Standard Time" },
  { label: "(UTC+07:00) Altai Standard Time", value: "Altai Standard Time" },
  { label: "(UTC+07:00) W. Mongolia Standard Time", value: "W. Mongolia Standard Time" },
  { label: "(UTC+07:00) North Asia Standard Time", value: "North Asia Standard Time" },
  { label: "(UTC+07:00) N. Central Asia Standard Time", value: "N. Central Asia Standard Time" },
  { label: "(UTC+07:00) Tomsk Standard Time", value: "Tomsk Standard Time" },
  { label: "(UTC+08:00) China Standard Time", value: "China Standard Time" },
  { label: "(UTC+08:00) North Asia East Standard Time", value: "North Asia East Standard Time" },
  { label: "(UTC+08:00) Singapore Standard Time", value: "Singapore Standard Time" },
  { label: "(UTC+08:00) W. Australia Standard Time", value: "W. Australia Standard Time" },
  { label: "(UTC+08:00) Taipei Standard Time", value: "Taipei Standard Time" },
  { label: "(UTC+08:00) Ulaanbaatar Standard Time", value: "Ulaanbaatar Standard Time" },
  { label: "(UTC+08:45) Aus Central W. Standard Time", value: "Aus Central W. Standard Time" },
  { label: "(UTC+09:00) Transbaikal Standard Time", value: "Transbaikal Standard Time" },
  { label: "(UTC+09:00) Tokyo Standard Time", value: "Tokyo Standard Time" },
  { label: "(UTC+09:00) North Korea Standard Time", value: "North Korea Standard Time" },
  { label: "(UTC+09:00) Korea Standard Time", value: "Korea Standard Time" },
  { label: "(UTC+09:00) Yakutsk Standard Time", value: "Yakutsk Standard Time" },
  { label: "(UTC+09:30) Cen. Australia Standard Time", value: "Cen. Australia Standard Time" },
  { label: "(UTC+09:30) AUS Central Standard Time", value: "AUS Central Standard Time" },
  { label: "(UTC+10:00) E. Australia Standard Time", value: "E. Australia Standard Time" },
  { label: "(UTC+10:00) AUS Eastern Standard Time", value: "AUS Eastern Standard Time" },
  { label: "(UTC+10:00) West Pacific Standard Time", value: "West Pacific Standard Time" },
  { label: "(UTC+10:00) Tasmania Standard Time", value: "Tasmania Standard Time" },
  { label: "(UTC+10:00) Vladivostok Standard Time", value: "Vladivostok Standard Time" },
  { label: "(UTC+10:30) Lord Howe Standard Time", value: "Lord Howe Standard Time" },
  { label: "(UTC+11:00) Bougainville Standard Time", value: "Bougainville Standard Time" },
  { label: "(UTC+11:00) Russia Time Zone 10", value: "Russia Time Zone 10" },
  { label: "(UTC+11:00) Magadan Standard Time", value: "Magadan Standard Time" },
  { label: "(UTC+11:00) Norfolk Standard Time", value: "Norfolk Standard Time" },
  { label: "(UTC+11:00) Sakhalin Standard Time", value: "Sakhalin Standard Time" },
  { label: "(UTC+11:00) Central Pacific Standard Time", value: "Central Pacific Standard Time" },
  { label: "(UTC+12:00) Russia Time Zone 11", value: "Russia Time Zone 11" },
  { label: "(UTC+12:00) New Zealand Standard Time", value: "New Zealand Standard Time" },
  { label: "(UTC+12:00) UTC+12", value: "UTC+12" },
  { label: "(UTC+12:00) Fiji Standard Time", value: "Fiji Standard Time" },
  { label: "(UTC+12:00) Kamchatka Standard Time", value: "Kamchatka Standard Time" },
  { label: "(UTC+12:45) Chatham Islands Standard Time", value: "Chatham Islands Standard Time" },
  { label: "(UTC+13:00) UTC+13", value: "UTC+13" },
  { label: "(UTC+13:00) Tonga Standard Time", value: "Tonga Standard Time" },
  { label: "(UTC+13:00) Samoa Standard Time", value: "Samoa Standard Time" },
  { label: "(UTC+14:00) Line Islands Standard Time", value: "Line Islands Standard Time" },
];
